### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vibratim** [benderstwin/docker-templates#4]
Hey,

I just wanted to ask if this template is useable. I tried to setup a docker container using this template and noting happens. It is marked as running but there are no files in the dirs.

The console of the container only shows this failure:
`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown`

thanks in advance

**Comment by benderstwin** [comment]
Sorry I didnt see this until now.  This template is working in unraid last I checked.  Per the notes, you have to have a traefik.toml in your config directory, that would be my first guess is that you didnt add that.

**Comment by vibratim** [comment]
Yeah allright i figured it out somehow and forgot about that issiue too.
But nevertheless thanks man :)

**Comment by benderstwin** [comment]
Right on, glad you got it working
