### ISSUE TITLE
unraid traefik template broken now that traefik:latest is version 2.0

### ISSUE THREAD

**Issue by linucksrox** [benderstwin/docker-templates#5]
Since Traefik released version 2.0, they made breaking changes requiring different labels and a new way of thinking about how routing works. As a result, the Bender-traefik.xml template no longer works out of the box because it's trying to use v1.x configuration labels with version 2.0 which is incompatible.

I would recommend as a quick fix changing the repository tag from `traefik:latest` to `traefik.v1.7` so it's up to date within the 1.x branch, and obviously as a longer term solution rewrite the whole thing for the version 2.0 release (if you want to).

**Comment by pixeldoc2000** [comment]
Thx @linucksrox.

Submitted patch #6 to fix it.

**Comment by justinforlenza** [comment]
Any update on the patch? Just found out about traefik, and wanted to start testing it out.
